<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.11 C:\Projects\vault\static\models\lab.glb --root /models/ --types --keepnames --printwidth 120 --precision 2 --isolated
-->

<script lang="ts">
	import type * as THREE from 'three';

	import type { Snippet } from 'svelte';
	import { T } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	let {
		fallback,
		error,
		children
	}: {
		children?: Snippet;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
	} = $props();

	type GLTFResult = {
		nodes: {
			Cube_1: THREE.Mesh;
			Cube_2: THREE.Mesh;
		};
		materials: {
			Material: THREE.MeshStandardMaterial;
			['Material.002']: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>('/models/lab.glb');
</script>

<T.Group dispose={false}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.PerspectiveCamera
			name="Camera"
			makeDefault={true}
			far={1000}
			near={0.1}
			fov={22.9}
			position={[0, 13.68, 28.15]}
		/>
		<T.Group name="Cube" position={[0, 2, -11]}>
			<T.Mesh
				name="Cube_1"
				geometry={gltf.nodes.Cube_1.geometry}
				material={gltf.materials.Material}
			>
				<T.MeshBasicMaterial color="blue" />
			</T.Mesh>
			<T.Mesh
				name="Cube_2"
				geometry={gltf.nodes.Cube_2.geometry}
				material={gltf.materials['Material.002']}
			>
				<T.MeshBasicMaterial color="red" />
			</T.Mesh>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.()}
</T.Group>
