<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.11 C:\Projects\vault\static\models\lab.glb --root /models/ --types --keepnames --printwidth 120 --precision 2 --isolated
-->

<script lang="js">
	import * as THREE from 'three';
	import { onMount } from 'svelte';

	import { T, useTask, useThrelte } from '@threlte/core';
	import { useGltf, OrbitControls, useViewport } from '@threlte/extras';

	let { fallback, error, children } = $props();

	const gltf = useGltf('/models/lab.glb');
	const { size, camera } = useThrelte();

	let groupRef = $state();
	let cameraDistance = $state(18.15);

	$effect(() => {
		if (groupRef && $camera && $size) {
			const box = new THREE.Box3().setFromObject(groupRef);
			const meshWidth = box.max.x - box.min.x;
			const meshHeight = box.max.y - box.min.y;

			const aspect = $size.width / $size.height;
			const vFov = $camera.fov * (Math.PI / 180);
			const hFov = 2 * Math.atan(Math.tan(vFov / 2) * aspect);

			const distanceForWidth = meshWidth / (2 * Math.tan(hFov / 2));
			cameraDistance = distanceForWidth * 1.1;
		}
	});
</script>

<T.Group dispose={false}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.PerspectiveCamera
			name="Camera"
			makeDefault={true}
			far={1000}
			near={0.1}
			fov={22.9}
			position={[0, 13.68, cameraDistance]}
		/>
		<T.Group name="Cube" position={[0, 2, 0]} bind:ref={groupRef}>
			<T.Mesh
				name="Cube_1"
				geometry={gltf.nodes.Cube_1.geometry}
				material={gltf.materials.Material}
			>
				<T.MeshBasicMaterial color="blue" />
			</T.Mesh>
			<T.Mesh
				name="Cube_2"
				geometry={gltf.nodes.Cube_2.geometry}
				material={gltf.materials['Material.002']}
			>
				<T.MeshBasicMaterial color="red" />
			</T.Mesh>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.()}
</T.Group>
